# Generated by Django 5.0.4 on 2024-05-06 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
